package lk.ijse.gdse67.green_shadow.Enum;

public enum Designation {
   MANAGER,SENIORASSISTANTMANAGER,ASSISTANTMANAGER,ADMINANDHRSTAFF,OFFICEASSISTANT,SENIORAGRONOMIST,AGRONOMIST,
    SOILSCIENTIST, SENIORTECHNICIAN,TECHNICIAN,SUPERVISOR,LABOUR;
}
